# Generated by Django 4.1 on 2022-10-11 09:52

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('sn', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id')),
                ('booker', models.CharField(max_length=30, verbose_name="Booker's name")),
                ('contact', models.CharField(max_length=15, verbose_name="Booker's contact")),
                ('charges', models.CharField(max_length=20, validators=[app.models.castValidator], verbose_name='Amount due($)')),
                ('paid', models.BooleanField(default=False)),
                ('goods', models.CharField(max_length=30)),
                ('pickup', models.CharField(max_length=100, verbose_name='pickup address')),
                ('delivery', models.CharField(max_length=100, verbose_name='delivery address')),
                ('doc1', models.FileField(blank=True, null=True, upload_to=app.models.doc1)),
                ('doc2', models.FileField(blank=True, null=True, upload_to=app.models.doc2)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=30, unique=True, verbose_name='id')),
                ('firstName', models.CharField(max_length=30, verbose_name='first name')),
                ('lastName', models.CharField(max_length=30, verbose_name='last name')),
                ('birthday', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'male'), ('F', 'female'), ('P', 'private')], max_length=1)),
                ('phone', models.CharField(max_length=15, verbose_name='phone number')),
                ('aptNo', models.IntegerField(verbose_name='apartment number')),
                ('laneNo', models.IntegerField(verbose_name='lane number')),
                ('street', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('nationality', models.CharField(max_length=30)),
                ('zipcode', models.IntegerField()),
                ('active', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(upload_to=app.models.driv)),
            ],
            options={
                'db_table': 'driver',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Loader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=30, unique=True, verbose_name='id')),
                ('firstName', models.CharField(max_length=30, verbose_name='first name')),
                ('lastName', models.CharField(max_length=30, verbose_name='last name')),
                ('birthday', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'male'), ('F', 'female'), ('P', 'private')], max_length=1)),
                ('phone', models.CharField(max_length=15, verbose_name='phone number')),
                ('aptNo', models.IntegerField(verbose_name='apartment number')),
                ('laneNo', models.IntegerField(verbose_name='lane number')),
                ('street', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('nationality', models.CharField(max_length=30)),
                ('zipcode', models.IntegerField()),
                ('active', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(upload_to=app.models.load)),
            ],
            options={
                'db_table': 'loader',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=30, unique=True, verbose_name='id')),
                ('firstName', models.CharField(max_length=30, verbose_name='first name')),
                ('lastName', models.CharField(max_length=30, verbose_name='last name')),
                ('birthday', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'male'), ('F', 'female'), ('P', 'private')], max_length=1)),
                ('phone', models.CharField(max_length=15, verbose_name='phone number')),
                ('aptNo', models.IntegerField(verbose_name='apartment number')),
                ('laneNo', models.IntegerField(verbose_name='lane number')),
                ('street', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('nationality', models.CharField(max_length=30)),
                ('zipcode', models.IntegerField()),
                ('active', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(upload_to=app.models.mech)),
            ],
            options={
                'db_table': 'mechanic',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freelancer', models.CharField(choices=[('driv', 'Driver'), ('mech', 'Mechanic'), ('load', 'Loader')], max_length=5, unique=True)),
                ('short_range', models.CharField(max_length=30, validators=[app.models.castValidator], verbose_name='pay/short-range trip in $')),
                ('mid_range', models.CharField(max_length=30, validators=[app.models.castValidator], verbose_name='pay/mid-range trip in $')),
                ('long_range', models.CharField(max_length=30, validators=[app.models.castValidator], verbose_name='pay/long-range trip in $')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('sn', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id')),
                ('category', models.CharField(choices=[('sh', 'Short Range'), ('md', 'Mid Range'), ('lg', 'Long Range')], max_length=3)),
                ('report', models.IntegerField(verbose_name='Expected report')),
                ('status', models.CharField(choices=[('one', 'Open'), ('two', 'Close')], max_length=3)),
                ('progress', models.CharField(choices=[('0', 'pending'), ('1', 'Departed'), ('2', 'Pickup'), ('3', 'Onroad'), ('4', 'Delivered'), ('5', 'Arrived')], default='0', max_length=2)),
                ('date', models.DateTimeField()),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='app.booking')),
                ('drivers', models.ManyToManyField(limit_choices_to={'active': False}, related_name='trips', to='app.driver')),
                ('loaders', models.ManyToManyField(limit_choices_to={'active': False}, related_name='trips', to='app.loader')),
                ('management', models.ForeignKey(limit_choices_to={'is_superuser': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to=settings.AUTH_USER_MODEL)),
                ('mechanics', models.ManyToManyField(limit_choices_to={'active': False}, related_name='trips', to='app.mechanic')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('G', 'Green'), ('R', 'Red'), ('Y', 'Gray')], max_length=5)),
                ('remark', models.CharField(max_length=30)),
                ('coord', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='app.trip')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('label', models.CharField(choices=[('D', 'Driver'), ('M', 'Management')], max_length=2)),
                ('status', models.CharField(choices=[('S', 'send'), ('D', 'delivered'), ('R', 'read')], max_length=2)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app.trip')),
            ],
        ),
    ]
