# Generated by Django 4.1.7 on 2023-09-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('manager', 'manager'), ('supervisor', 'supervisor'), ('agent', 'agent'), ('payroll', 'payroll')], help_text='This field define the user access level to the transit panel.', max_length=12),
        ),
    ]
