# Generated by Django 4.1 on 2023-02-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='active',
        ),
        migrations.RemoveField(
            model_name='loader',
            name='active',
        ),
        migrations.RemoveField(
            model_name='mechanic',
            name='active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='currentTrip_id',
        ),
        migrations.AlterField(
            model_name='report',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=8),
        ),
        migrations.AlterField(
            model_name='report',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
