# Generated by Django 4.1 on 2022-12-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_agent',
            field=models.BooleanField(default=False, help_text='Designates that this user have access to the trip reporting part of this web-app'),
        ),
        migrations.AlterField(
            model_name='user',
            name='office_line',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Office-line'),
        ),
        migrations.AlterField(
            model_name='user',
            name='personal_line',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Personal-line'),
        ),
    ]
