# Generated by Django 4.1.7 on 2023-12-31 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_trip_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='latest_report',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_trip', to='app.report'),
        ),
    ]
