# Generated by Django 4.1.7 on 2024-02-23 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_report_latitude_alter_report_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(max_length=40, verbose_name="Company's name"),
        ),
        migrations.AlterField(
            model_name='report',
            name='progress',
            field=models.CharField(choices=[('0', 'Pending'), ('1', 'Departed'), ('2', 'Pickup'), ('3', 'Onroad'), ('4', 'Delivered'), ('5', 'Arrived')], default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='transporter',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='closed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='latest_report',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_trip', to='app.report'),
        ),
    ]
